FROM gradle:jdk11 as compile

WORKDIR /app
COPY . /app

RUN gradle --no-parallel --no-daemon bootJar

FROM alpine:3.14

RUN  apk update \
  && apk upgrade \
  && apk add --update openjdk11-jre-headless tzdata curl unzip bash \
  && rm -rf /var/cache/apk/*

WORKDIR /app
COPY --from=compile /app/build/libs/emr-0.0.1-SNAPSHOT.jar /app/emr.jar

EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "/app/emr.jar" ]
