version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
      - "5005:5005"
    volumes:
      - ./:/app
    working_dir: /app
    user: appuser
    command: ./gradlew --project-cache-dir /tmp/gradle-cache bootRun
    depends_on:
      - db
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    environment:
      PGDATA: "/pgdata"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/pgdata
      - /etc/passwd:/etc/passwd:ro
    user: 1000:1000
