version: '3'

volumes:
  pgdata:

services:
  app:
    build: .
    ports:
      - '8080:8080'
      - "5005:5005"
    volumes:
      - ./:/app
    working_dir: /app
    user: appuser
    command: ./gradlew --project-cache-dir /tmp/gradle-cache bootRun
    depends_on:
      - db
    links:
      - mailtrap
      - db
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailtrap:
    image: msztolcman/sendria:v2.2.2.0
    ports:
      - "127.0.0.1:9080:1080"
