version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    user: appuser
    command: ./gradlew --project-cache-dir /tmp/gradle-cache test
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    environment:
      PGDATA: "/pgdata"
    env_file:
      - .env
    volumes:
      - ./pgdata:/pgdata
      - /etc/passwd:/etc/passwd:ro
    user: 1000:1000
