package xyz.l7ssha.emr.configuration.security

enum class PermissionType {
    ADMIN,
    CREATE_USERS, VIEW_USERS,
    VIEW_REPORTS,
    CREATE_PRODUCTS, REMOVE_PRODUCTS,
    CREATE_CATEGORIES, REMOVE_CATEGORIES,
    CREATE_FEATURES, REMOVE_FEATURES
}
