CREATE TABLE currencies
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         BIGINT                                  NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by         BIGINT,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(10)                             NOT NULL,
    symbol             VARCHAR(3)                              NOT NULL,
    alternative_symbol VARCHAR(3)                              NOT NULL,
    CONSTRAINT pk_currencies PRIMARY KEY (id)
);

CREATE TABLE product_categories
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by BIGINT,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    parent     BIGINT,
    assignable BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_product_categories PRIMARY KEY (id)
);

CREATE TABLE product_categories_children
(
    category_id BIGINT NOT NULL,
    children_id BIGINT NOT NULL
);

CREATE TABLE product_feature_groups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by BIGINT,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    title      VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_product_feature_groups PRIMARY KEY (id)
);

CREATE TABLE product_feature_values
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by             BIGINT                                  NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by             BIGINT,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    name                   VARCHAR(30)                             NOT NULL,
    product_feature_groups BIGINT,
    CONSTRAINT pk_product_feature_values PRIMARY KEY (id)
);

CREATE TABLE product_features
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by             BIGINT                                  NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by             BIGINT,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    name                   VARCHAR(255)                            NOT NULL,
    title                  VARCHAR(255),
    product_feature_groups BIGINT,
    product_features       BIGINT,
    CONSTRAINT pk_product_features PRIMARY KEY (id)
);

CREATE TABLE product_images
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(32)                             NOT NULL,
    external_id UUID                                    NOT NULL,
    CONSTRAINT pk_product_images PRIMARY KEY (id)
);

CREATE TABLE product_prices
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by BIGINT,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    value      DOUBLE PRECISION                        NOT NULL,
    currencies BIGINT,
    CONSTRAINT pk_product_prices PRIMARY KEY (id)
);

CREATE TABLE product_tags
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by BIGINT,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_product_tags PRIMARY KEY (id)
);

CREATE TABLE products
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_at              TIMESTAMP WITHOUT TIME ZONE,
    created_by              BIGINT                                  NOT NULL,
    created_at              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by              BIGINT,
    updated_at              TIMESTAMP WITHOUT TIME ZONE,
    name                    VARCHAR(30)                             NOT NULL,
    description             VARCHAR(16384)                          NOT NULL,
    sku                     VARCHAR(30)                             NOT NULL,
    stock                   INTEGER                                 NOT NULL,
    producer                VARCHAR(30)                             NOT NULL,
    model                   VARCHAR(30)                             NOT NULL,
    producer_product_number VARCHAR(30)                             NOT NULL,
    condition               VARCHAR(255)                            NOT NULL,
    ean                     VARCHAR(15)                             NOT NULL,
    product_categories      BIGINT,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE products_features_values
(
    product_id         BIGINT NOT NULL,
    features_values_id BIGINT NOT NULL
);

CREATE TABLE products_images
(
    product_id BIGINT NOT NULL,
    images_id  BIGINT NOT NULL
);

CREATE TABLE products_prices
(
    product_id BIGINT NOT NULL,
    prices_id  BIGINT NOT NULL
);

CREATE TABLE products_tags
(
    product_id BIGINT NOT NULL,
    tags_id    BIGINT NOT NULL
);

ALTER TABLE users
    ADD created_by BIGINT;

ALTER TABLE users
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

UPDATE users
    SET created_by = (SELECT id from users WHERE email = 'admin@example.com' LIMIT 1),
        created_at = now(),
        password_expired = true;

ALTER TABLE users
    ADD updated_by BIGINT;

ALTER TABLE users
    ALTER COLUMN created_by SET NOT NULL;

ALTER TABLE currencies
    ADD CONSTRAINT uc_currencies_alternative_symbol UNIQUE (alternative_symbol);

ALTER TABLE currencies
    ADD CONSTRAINT uc_currencies_name UNIQUE (name);

ALTER TABLE currencies
    ADD CONSTRAINT uc_currencies_symbol UNIQUE (symbol);

ALTER TABLE product_categories_children
    ADD CONSTRAINT uc_product_categories_children_children UNIQUE (children_id);

ALTER TABLE product_categories
    ADD CONSTRAINT uc_product_categories_name UNIQUE (name);

ALTER TABLE product_feature_groups
    ADD CONSTRAINT uc_product_feature_groups_name UNIQUE (name);

ALTER TABLE product_features
    ADD CONSTRAINT uc_product_features_name UNIQUE (name);

ALTER TABLE product_images
    ADD CONSTRAINT uc_product_images_external UNIQUE (external_id);

ALTER TABLE product_images
    ADD CONSTRAINT uc_product_images_name UNIQUE (name);

ALTER TABLE product_tags
    ADD CONSTRAINT uc_product_tags_name UNIQUE (name);

ALTER TABLE products
    ADD CONSTRAINT uc_products_name UNIQUE (name);

ALTER TABLE products
    ADD CONSTRAINT uc_products_sku UNIQUE (sku);

CREATE UNIQUE INDEX idx_ef755ae5746cea3d98be5355a ON products (sku);

ALTER TABLE currencies
    ADD CONSTRAINT FK_CURRENCIES_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE currencies
    ADD CONSTRAINT FK_CURRENCIES_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES users (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_PRODUCT_CATEGORIES FOREIGN KEY (product_categories) REFERENCES product_categories (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES users (id);

ALTER TABLE product_categories
    ADD CONSTRAINT FK_PRODUCT_CATEGORIES_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE product_categories
    ADD CONSTRAINT FK_PRODUCT_CATEGORIES_ON_PARENT FOREIGN KEY (parent) REFERENCES product_categories (id);

CREATE INDEX idx_a9ab3d5223e1b1016c249ba4a ON product_categories (parent);

ALTER TABLE product_categories
    ADD CONSTRAINT FK_PRODUCT_CATEGORIES_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES users (id);

ALTER TABLE product_features
    ADD CONSTRAINT FK_PRODUCT_FEATURES_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE product_features
    ADD CONSTRAINT FK_PRODUCT_FEATURES_ON_PRODUCT_FEATURES FOREIGN KEY (product_features) REFERENCES product_feature_groups (id);

ALTER TABLE product_features
    ADD CONSTRAINT FK_PRODUCT_FEATURES_ON_PRODUCT_FEATURE_GROUPS FOREIGN KEY (product_feature_groups) REFERENCES product_feature_groups (id);

ALTER TABLE product_features
    ADD CONSTRAINT FK_PRODUCT_FEATURES_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES users (id);

ALTER TABLE product_feature_groups
    ADD CONSTRAINT FK_PRODUCT_FEATURE_GROUPS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE product_feature_groups
    ADD CONSTRAINT FK_PRODUCT_FEATURE_GROUPS_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES users (id);

ALTER TABLE product_feature_values
    ADD CONSTRAINT FK_PRODUCT_FEATURE_VALUES_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE product_feature_values
    ADD CONSTRAINT FK_PRODUCT_FEATURE_VALUES_ON_PRODUCT_FEATURE_GROUPS FOREIGN KEY (product_feature_groups) REFERENCES product_features (id);

ALTER TABLE product_feature_values
    ADD CONSTRAINT FK_PRODUCT_FEATURE_VALUES_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES users (id);

ALTER TABLE product_prices
    ADD CONSTRAINT FK_PRODUCT_PRICES_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE product_prices
    ADD CONSTRAINT FK_PRODUCT_PRICES_ON_CURRENCIES FOREIGN KEY (currencies) REFERENCES currencies (id);

ALTER TABLE product_prices
    ADD CONSTRAINT FK_PRODUCT_PRICES_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES users (id);

ALTER TABLE product_tags
    ADD CONSTRAINT FK_PRODUCT_TAGS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE product_tags
    ADD CONSTRAINT FK_PRODUCT_TAGS_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_UPDATED_BY FOREIGN KEY (updated_by) REFERENCES users (id);

ALTER TABLE product_categories_children
    ADD CONSTRAINT fk_procatchi_on_category FOREIGN KEY (category_id) REFERENCES product_categories (id);

ALTER TABLE product_categories_children
    ADD CONSTRAINT fk_procatchi_on_children FOREIGN KEY (children_id) REFERENCES product_categories (id);

ALTER TABLE products_features_values
    ADD CONSTRAINT fk_profeaval_on_feature_value FOREIGN KEY (features_values_id) REFERENCES product_feature_values (id);

ALTER TABLE products_features_values
    ADD CONSTRAINT fk_profeaval_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_images
    ADD CONSTRAINT fk_proima_on_image FOREIGN KEY (images_id) REFERENCES product_images (id);

ALTER TABLE products_images
    ADD CONSTRAINT fk_proima_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_prices
    ADD CONSTRAINT fk_propri_on_price FOREIGN KEY (prices_id) REFERENCES product_prices (id);

ALTER TABLE products_prices
    ADD CONSTRAINT fk_propri_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_tags
    ADD CONSTRAINT fk_protag_on_product FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE products_tags
    ADD CONSTRAINT fk_protag_on_tag FOREIGN KEY (tags_id) REFERENCES product_tags (id);

ALTER TABLE users
    ALTER COLUMN created_at SET NOT NULL;
