CREATE TABLE user_permissions
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user_permissions PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    enabled  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_permissions
(
    user_id        BIGINT NOT NULL,
    permissions_id BIGINT NOT NULL,
    CONSTRAINT pk_users_permissions PRIMARY KEY (user_id, permissions_id)
);

ALTER TABLE user_permissions
    ADD CONSTRAINT uc_user_permissions_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users_permissions
    ADD CONSTRAINT fk_useper_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users_permissions
    ADD CONSTRAINT fk_useper_on_user_permission FOREIGN KEY (permissions_id) REFERENCES user_permissions (id);
