CREATE TABLE refresh_tokens
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user"          BIGINT                                  NOT NULL,
    refresh_token   VARCHAR(255)                            NOT NULL,
    expiration_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_refresh_token UNIQUE (refresh_token);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY ("user") REFERENCES users (id);
