CREATE TABLE forgot_password_tokens
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    token           VARCHAR(255)                            NOT NULL,
    expiration_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_forgot_password_tokens PRIMARY KEY (id)
);

ALTER TABLE forgot_password_tokens
    ADD CONSTRAINT uc_forgot_password_tokens_token UNIQUE (token);

ALTER TABLE forgot_password_tokens
    ADD CONSTRAINT uc_forgot_password_tokens_user UNIQUE (user_id);

ALTER TABLE forgot_password_tokens
    ADD CONSTRAINT FK_FORGOT_PASSWORD_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);
