CREATE TABLE reset_password_tokens
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    token           VARCHAR(255)                            NOT NULL,
    expiration_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_reset_password_tokens PRIMARY KEY (id)
);

ALTER TABLE users
    ADD password_expired BOOLEAN DEFAULT false;

ALTER TABLE users
    ALTER COLUMN password_expired SET NOT NULL;

ALTER TABLE reset_password_tokens
    ADD CONSTRAINT uc_reset_password_tokens_token UNIQUE (token);

ALTER TABLE reset_password_tokens
    ADD CONSTRAINT uc_reset_password_tokens_user UNIQUE (user_id);

ALTER TABLE reset_password_tokens
    ADD CONSTRAINT FK_RESET_PASSWORD_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE forgot_password_tokens
    DROP CONSTRAINT fk_forgot_password_tokens_on_user;

DROP TABLE forgot_password_tokens CASCADE;
