name: Push CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - uses: burrunan/gradle-cache-action@v1
      name: Assemble project
      with:
        job-id: jdk${{ matrix.jdk }}
        arguments: --scan --no-parallel --no-daemon assemble

  lint:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: burrunan/gradle-cache-action@v1
        name: Run detekt
        with:
          job-id: jdk${{ matrix.jdk }}
          arguments: --scan --no-parallel --no-daemon detekt detektTest

  test:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: burrunan/gradle-cache-action@v1
        name: Run tests
        with:
          job-id: jdk${{ matrix.jdk }}
          arguments: --scan --no-parallel --no-daemon test --tests "*"

  build-image:
    runs-on: ubuntu-latest
    needs: [ test, lint]

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_PUSH_IMAGE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile.deploy
          push: true
          tags: latest
